--PEDIR PROFESSOR DATA PARA CONSULTA 5
--COLOCAR UM PRODUTO COM ESTOQUE MAIOR QUE 100
--COLOCAR MAIS DE UM FUNCIONÁRIO DE UMA MESMA CIDADE
--COLOCAR PRODUTOS COM VALORES ACIMA DE 50
--COLOCAR UM FUNCIONARIO COM MAIS DE 3K DE SALARIO
--COLOCAR FUNCIONARIOS QUE TENHAM "OPERADOR" NO CARGO
--COLOCAR UM FORNECEDOR SEM TELEFONE
--PEDIR PALAVRA/TRECHO/LETRA PARA PROFESSOR NA CONSULTA 12
--COLOCAR UMA ORDEM DE PRODUCAO COM STATUS "CONCLUIDA"

/*5 setores;
10 funcionários;
10 produtos;
5 categorias;
5 fornecedores;
15 ordens de produção;
10 registros de qualidade.*/

INSERT INTO Funcionarios(CPF, nomeFuncionario, cargoFuncionario, salarioFuncionario, dataDeAdmissao)
VALUES(
    12345678910, 'Cleber'
);